version: '3.8'

services:
  noxhime:
    build:
      context: .
      dockerfile: local-dev.dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
