name: Debug Workflow

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable tmate debugging session'
        required: false
        default: false
        type: boolean

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: List Environment
      run: |
        echo "Node version:"
        node -v
        echo "NPM version:"
        npm -v
        echo "Directory structure:"
        ls -la
        echo "Environment variables:"
        env | sort
        
    - name: Build Project
      run: npm run build
      
    - name: Setup tmate session
      if: ${{ inputs.debug_enabled }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
